### ISSUE TITLE
Strange entries in apache error log on queries to http://applejack.science.ru.nl/tmi/

### ISSUE THREAD

**Issue by proycon** [fbkarsdorp/tmi#11]
I get some weird output in the apache error log whenever a POST query is made to http://applejack.science.ru.nl/tmi:

[Sat Jan 16 21:26:31.058292 2016] [:error] [pid 32502] description
[Sat Jan 16 21:26:31.058432 2016] [:error] [pid 32502] additional

Not too big an issue but it's cluttering the logs a bit..

**Comment by fbkarsdorp** [comment]
App is offline now, so I'm closing this for the moment. Thanks.
